### ISSUE TITLE
Duplicate examples

### ISSUE THREAD

**Issue by whabilly** [sbcshop/Makerpad_Pro_Software#1]
Hi, it appears the Demo_Camera.ino and Demo_TouchWorking.ino examples are identical. Please update the examples. Thanks.

**Comment by sbcshop3** [comment]
Hi there, thank you pointing this out. Now fixed with touch demo code; please take a look: https://github.com/sbcshop/Makerpad_Pro_Software/tree/main/examples/Demo_TouchWorking
